### ISSUE TITLE
Not working on iOS

### ISSUE THREAD

**Issue by kpourdeilami** [madebymany/sir-trevor-js#229]
Hi,

I'm trying to use the sir trevor in a hybrid app with Ionic and Cordova but for some reason it doesn't work. Only the first + is clickable and I can't type anything in the text block.

Any thoughts on how I can make this to work on iOS?

**Comment by yzhao30** [comment]
Try to put 
```
    <style>
    *[contenteditable] {
        -webkit-user-select: auto !important;
    }
    </style>
```
in your code or in the css file.

**Comment by raffij** [comment]
I'll take a look and see what's going on.

**Comment by SgtOddball** [comment]
I always assumed this was because of scribe not supporting mobile browsers? Admittedly I've not tested it massively on iOS (since I'm not a fan of iThings.. shock horror etc.) but its always behaved correctly for me on chrome mobile on Android 4.3 and 5.

**Comment by raffij** [comment]
@SgtOddball yeah this is true. Scribe says it should work, but don't guarantee. Whereas in Internet Explorer there are known issues.

**Comment by SgtOddball** [comment]
@raffij ....Well it's internet explorer.... that's pretty much a given that it'll have issues (known and unknown...). 

At least they've finally taken the sane step of trying to kill off IE8-10 since IE11 isn't actually that bad (it's true.. the developer console is miles better than safaris and some nice features that chrome doesn't have... I still prefer firebug but better the devil you know). 

Haven't really tried it in Edge yet in anger. Might have a look into it later to see how badly it breaks.

**Comment by raffij** [comment]
@SgtOddball at present the way scribe deal with removing placemarkers causes an issue with ie when you are editing text that has already been written.

**Comment by SgtOddball** [comment]
@raffij It was more a generalised statement. I've been working with IE long enough to have developed a very healthy hatred of those who created IE6,7, 8 and 9. 10 showed promise and IE11 did alot to repair some of the damage done to the name of internet explorer.... And who ever the hell created IE5, word fail me (and lets not forget IE5.5 for mac... yes that was once a thing).

**Comment by SgtOddball** [comment]
Oh and on Edge, yes, you're right it does have some very odd behaviour around editing text so I'd assume it's the same issue.
