### ISSUE TITLE
Image upload example

### ISSUE THREAD

**Issue by misterGF** [madebymany/sir-trevor-js#258]
Hi!

The gist for an uploader example in the documentation doesn't led to anything.
I struggled a little to get it to work properly without ST throwing an error.
Found out that it just needs a valid json response. Created a gist to help others that may
be having the same issue. Hopefully the documentation can be updated.

https://gist.github.com/misterGF/b7bbb5ecd5b043897b39 

Thanks!
Gil

**Comment by ninjabiscuit** [comment]
Hi. Just going through some old issues and realised we didn't get back to you about this. My bad. An image upload tutorial has been updated in the documentation here: http://madebymany.github.io/sir-trevor-js/setting-up-image-uploading.html

**Comment by SgtOddball** [comment]
Ooh that reminds me. Did anything ever get done about sending an request back to server when deleting an image block or is there an event that could be captured (along with the images uid) to handle this? 

I've got something inplace already mind you but it's a tad hacky at best (comparing images on loading the page vs. images on saving the page and discarding any misc. images once finished) but something more immediate would be handy and less reliant on having to manage it during the page save.

**Comment by rnjailamba** [comment]
SgtOddball can you please post a gist of what you have in mind!

**Comment by SgtOddball** [comment]
I've been both on hols and working on other projects lately so I haven't had time to go back to this. 

In the end I put in some code at the backend that checked what the previous content (with images) was and compares it with the new content (sans images), it then removes the images in the background. This also checks for images that might have been uploaded and then removed, but since it's all custom code for my projects it's not that portable.
