### ISSUE TITLE
Changes and no documentation update

### ISSUE THREAD

**Issue by Siron** [madebymany/sir-trevor-js#289]
Hello,

Great work on the new version. I recently upgraded from version 0.3.0 to 0.4.3. I used to use this code * https://gist.github.com/Siron/1b4f5a05b5fdfabaa17a to save. Now I am struggling to figure out how to actually save content * https://gist.github.com/Siron/27195a0f08b069db988d 

Now, I am getting odd behaviour where newly created blocks aren't in the store so when I try to save the store doesn't contain the new blocks. And also, when I loads and build data into the editor I am getting repeated groups. He is the code used to build the articles - https://gist.github.com/Siron/8062ddab309d443efedf

Any idea which functions have replaced the ones I have been using?

Thanks in advance.

**Comment by gimmixAT** [comment]
Hi, I am currently having the same problem. So far I have figured out that you have to override `_serializeData` instead of `toData` and return the object instead of calling `this.setData(obj)`

**Comment by ninjabiscuit** [comment]
Hi.

It looks like you're trying to intercept the dataStore rather than saving
the data through a text area. ST wasn't designed wih this scenario in mind
but it is something that is on our roadmap. It's difficult for me to help
either of you with this problem without seeing a more fully fledged
example.

**Comment by gimmixAT** [comment]
Yup, but that is the procedure described in the examples/javascript/example_block.js which tells me to override toData for saving my data. This doesn't work anymore since there has been a a lot of changes in #155 which has been released in 0.4.0 but the example block hasn't been updated accordingly in a while hence the original issue title.

As for me, the method described above works prefectly fine.
