### ISSUE TITLE
ie10 support and the new beta

### ISSUE THREAD

**Issue by butsjoh** [madebymany/sir-trevor-js#291]
Hi,

I was looking into what changed in the beta 0.5 release and i saw the decision was made to use scribe for the content editable parts (https://github.com/madebymany/sir-trevor-js/pull/274). But it seems that the scribe editor has little to none support for internet explorer at all (based on https://github.com/guardian/scribe/issues/286). So i this going to affect the support of sir trevor as well? If so i think the readme on the main page should be updated to reflect that. Another suggestion could be to no deeply integrate scribe into the core but let the core be able to deal with text parts that could potentially be different editors.

**Comment by ninjabiscuit** [comment]
Hi. thanks for your feedback. We're looking at using scribe as the basis for our text blocks as it does such a great job of rationalising contenteditable across browsers. For more information about the discussions we had and why we decided to do this, take a look at [this comment](https://github.com/madebymany/sir-trevor-js/issues/314#issuecomment-78260198). 

Since we're integrating Scribe with ST core, our browser support will probably closely track theirs. So you're right, IE10 support will be an issue for ST until the Scribe maintainers decide to work on it.

Currently the master branch and the latest 3 releases (0.5.0-betaN) should be considered unstable (hence the beta suffix). We will update the documentation to reflect current browser support but probably only when we're ready to bring the 0.5.0 release out of beta.

I hope that makes sense and goes some way to answering your question.
