### ISSUE TITLE
Heading Block issue with excessive <br> elements

### ISSUE THREAD

**Issue by gmoreira** [madebymany/sir-trevor-js#318]
Not really sure where to fix this one - could be something deep in the Scribe component as I am still investigating.

When you create a new Heading block and save it, you get something like this:

Firefox `{"data":[{"type":"heading","data":{"text":"Test<br>","isHtml":true}}]}`
Chrome `{"data":[{"type":"heading","data":{"text":"Test","isHtml":true}}]}`

When you load this data back into the editor for each respective browser and save it again, you get this:

Firefox `{"data":[{"type":"heading","data":{"text":"Test<br><br>","isHtml":true}}]}`
Chrome `{"data":[{"type":"heading","data":{"text":"Test<br>","isHtml":true}}]}`

Rinse and repeat:

Firefox `{"data":[{"type":"heading","data":{"text":"Test<br><br><br>","isHtml":true}}]}`
Chrome `{"data":[{"type":"heading","data":{"text":"Test<br><br>","isHtml":true}}]}`

Etc... so essentially, it seem to continually compound more `<br>` elements at the end of the data each time you save the data.

Any thoughts on best/place to attack this issue?

**Comment by zgryw** [comment]
It looks like it's a default behavior in Scribe when you disable block level tags (which I did, because we don't want block level tags inside of headings).

I remember from reading issues on Scribe that they have to put `<br>` inside of inline tags, because otherwise you can't place the caret inside (yay contenteditable!).

We can easily deal with the `<br>` at the end of the data on our own, or see what people from Scribe think of it.

**Comment by zgryw** [comment]
OH! Maybe it is because we're initialising Scribe with a blank state and then setting data on it!
