### ISSUE TITLE
When is the next release?

### ISSUE THREAD

**Issue by markwpearce** [madebymany/sir-trevor-js#321]
What's the estimated date for the next stable release of Sir Trevor?

Thanks!

**Comment by zgryw** [comment]
As you can see we're in the middle of migration to Scribe as main text editor and HTML instead of markdown. Our aim is to release (0.5.0) as soon as this is done, and then follow up with other bug fixes. I can't give you an estimation now, I'm in the middle of rewriting list block to be more in line with SirTrevor approach - after that will asses what other things have to be done, but it seems that all other native blocks are ready for final release.

Next is just updating the documentation to represent the current state. We hope to have more of a timeline soon.

**Comment by ninjabiscuit** [comment]
Unless there are any objections I'm going to close this.
