### ISSUE TITLE
Markdown in 0.5.x

### ISSUE THREAD

**Issue by stopdesign** [madebymany/sir-trevor-js#369]
What is the future of Markdown in 0.5.x branch?
Is it completely removed?

**Comment by ninjabiscuit** [comment]
Hi

We will be supporting legacy markdown for old data so that an upgrade to 5.0.0 will mean backwards compatibility with data saved under previous versions of ST.

However, old content containing markdown will be converted to html on edit and will then be saved as html so that we can phase out markdown support over time.

The does not preclude you from creating your own custom markdown blocks and doing whatever you like with them. However, core ST will no longer create or save markdown or transform it in any way.

Hopefully that makes things a little clearer.

We are very close to a 5.0.0 release and will be blogging about the change as soon as it happens

-- 
Andrew Walker ["@ninjabiscuit", "07886655448"]
http://madebymany.com

On 20 July 2015 at 18:05:31, Gregory Zhizhilkin (notifications@github.com) wrote:

What is the future of Markdown in 5.x.x branch?
Is it completely removed?

**Comment by ninjabiscuit** [comment]
Closing this unless you have any further questions
