### ISSUE TITLE
Text colouring

### ISSUE THREAD

**Issue by SgtOddball** [madebymany/sir-trevor-js#371]
Does anyone know if there's currently a way to colour highlighted text or is it more of a scribe plug-in? 

If it's not something thats been done so far I might have a look to see what would be involved in getting it added.

**Comment by ninjabiscuit** [comment]
AFAIK there is no text colouring plugin for ST. This is something that would have to implemented as a plugin for scribe that integrates with the format bar. 

The reason we've never attempted anything like this with ST is that it's contrary to the core philosophy. We try to allow as little presentational manipulation as possible for editors unless specifically allowed in the context of the design.

That's not to say that you shouldn't attempt this. The context for your design may allow for highlighted test and that's fine. It's just not a core ST concern. I would be interested to see something like this developed as a plugin or tutorial to make the functionality available to others.

One word of warning. We're looking at refactoring the format bar soon and much of the core API. We will be looking at solidifying a public API that will be less subject to change. This won't happen over night but I thought it would only be fair to give you warning as this may effect the work you're planning.

Let us know how you get on with building this!

**Comment by SgtOddball** [comment]
I guessed as much, it was just on the off chance incase I'd missed anything. I was just trying to avoid doing much for scribe as it's reads even more like voodoo magic than Sir Trev (at least the blocks for Sir Trev make sense as to what they're upto). 

Will do, now I've just got to figure how scribe plug-ins work...

On a related note, any idea when/what version you'll be looking at changing the format bar? And will it still be using scribe then as it's core editor? I ask mainly as what I've changed with the format bar so far has been just to add the extra functions from scribe in as part of the Sir Trevor startup options making it a doddle once you know the trick.

**Comment by ninjabiscuit** [comment]
We're planning the work now and hoping to have it done before the next major version. However, that may not be released for a while. If you share what you've done with the format bar so far. We'll try to take in to account your use case when making changes. Although I can't promise that we can accommodate you fully.

**Comment by andrewsprinz** [comment]
https://en.wikipedia.org/wiki/Separation_of_presentation_and_content

Grey area, I admit.

From the beginning we tried to follow the HTML spec in order to define this
split.

i.e. emphasis (em, strong) as inline semantics; and p, blockquote etc. as
block level. Both have have meaning, grammatically.

... colours, alignment, etc. do not.

For the user, I prefer to think of ST as a *content* editor. How that
content is displayed to the end-user should remain in the hands of the
designer.

Less democratically; content editors can not, and should not, be trusted
with presentation. Have you used Eventbrite?

Understand that this is a learning curve for editors used to WYSIWYG, but
it’s a curve worth learning. They’ll thank you when you when they realise
that they don’t have to give a shit about formatting — whatever they write
will look beautiful.

… assuming, that is, your front-enders are working closely with editors and
visual designers to define what beautiful means.

Not easy, but worth the effort.

A

**Comment by ilyaporopudas** [comment]
:+1: @andrewsprinz :smile:

**Comment by SgtOddball** [comment]
@andrewsprinz Whilst I understand the difference, it was more a case of I've got at least one potential user for the content that insists on wording being coloured in certain cases (namely a brand name with colours), Whilst there are ways around this (I wrote a function that looks for *every* bloody instance of his brand name and assigned the colour that way. That shut him up) It would just be a useful feature for content. 

There are also instances where colour can give context to content. (Just look at the colours github throws up for inline or block code) but I concede the point and I'll have a look at this in my own time. 

Also @ilyaporopudas , thanks for that. Now I've just got to figure out Scribe works ```<grumble></grumble>```

**Comment by SgtOddball** [comment]
Oh and @andrewsprinz ... the final paragraph means getting in a room with me, myself and I :smile: but then that's why I went with Sir Trev, it removes the restrictions of wysiwyg editors being thought of like a word document (you know A4 sized and fixed) and makes it easier to understand that the content can be flexible and responsive/adaptive/```<insert>Multi platform term of choice</insert>```. 

But I digress...
