### ISSUE TITLE
dependencies vs devDependencies in package.json

### ISSUE THREAD

**Issue by lsirivong** [madebymany/sir-trevor-js#398]
Hello!

We're trying to include sir-trevor v0.5.0 in our package.json for our site which is also compiled through webpack, and `npm install` ends up omitting most of the required dependencies (such as lodash). We end up seeing errors like:

```
ERROR in ./~/sir-trevor/src/lodash.js
Module not found: Error: Cannot resolve module 'lodash.isempty' in /app/node_modules/sir-trevor/src
 @ ./~/sir-trevor/src/lodash.js 3:18-43
```

I've cloned the repo and if I update package.json to reference those dependencies as `dependencies` rather than `devDependencies` they get installed correctly in the host app. Does this seem like the correct approach or is there some other way that I've overlooked?

Happy to submit a PR if this would make sense.

**Comment by raffij** [comment]
@lsirivong are you including the npm version or pointing to a github tag in your package.json

**Comment by lsirivong** [comment]
Should be the npm version. It's defined like so:
```javascript
{
	// [snip]
	"dependencies": {
		// [...snip...]
		"sir-trevor": "0.5.0",
		// [...snip...]
	}
}
```

**Comment by raffij** [comment]
Hi @lsirivong,

I see what you are doing now.
At present sir-trevor isn't package in a way that allows you to do what you'd like.

If you wish to use sir-trevor in this way you should use the combined css / js in the root dir.

Otherwise you could try installing the devDependencies in the node_modules dir and see if that does as required.

Hope that helps.

**Comment by chrishutchinson** [comment]
+1 for this, I have the same requirement and error messages

**Comment by toddmoorega** [comment]
+1 for this, the entry for the npm package is a bit off `"main": "build/sir-trevor.js",`

I think you should package this so that a built version of sir-trevor is available through the entry. Or are you using it for something?

**Comment by raffij** [comment]
Yeah this is something we need to look at as more and more of you are using the npm package and wanting to consolidate dependencies where possible. We'll take a look and see what we think is best.

**Comment by ninjabiscuit** [comment]
@toddmoorega the `main` part of the `package.json` is configured that way because Scribe is AMD only. We have to compile the package because people using browserify cannot load the AMD dependency.

**Comment by toddmoorega** [comment]
I think it's as simple as moving the some devDeps to deps and then at least in terms of webpack that'll fix the issue.

Appreciate though that the webpack user is not the main use case. I moved the dependencies in my fork's next branch (although I've kept both devDeps and Deps for now).

For now I've also just committed the built folder (which I need to change). I'll try implementing an npm post install so that it triggers the build after install.

**Comment by raffij** [comment]
@ninjabiscuit yeah that's a good point. The issue we need to overcome is someone using a github source through npm. So maybe a git hook which compiles the build and handles it as binary. Otherwise some sort of dev env postinstall that installs all dev deps and builds the source in the right folder.

Scribe will also consider a non amd pr and their project isn't that big.
https://github.com/guardian/scribe/issues/83#issuecomment-150270904
