### ISSUE TITLE
edit/ update data on an existing instance with agularjs

### ISSUE THREAD

**Issue by ilgianfra** [madebymany/sir-trevor-js#404]
Hi,

In my controller angular I create the new instance of sirTrevor like this:

``` javascript
  function initSirTrevor(){
    editorSt = new SirTrevor.Editor(
      {
        el: $('.js-st-instance'),
        blockTypes: ['Text', 'Image', 'Heading'],
        required: ['Text']
      }
    );
}
```

But i call this function if there is no other instances created, so i check it:

``` javascript
  if(SirTrevor.config.instances.length <= 0){
    initSirTrevor();
  }
```

Like this i can call always the first instance, but when I go in the edit page I get the first instance and i put my block because they are stored in my server.

``` javascript
        var instance = SirTrevor.getInstance(0);

        // create new blocks for the updated data
        project._description.forEach(function(block) {
          instance.mediator.trigger('block:create', block.type, block.data);
        });
```

In project._description i have my stored data, and in fact it works well. But at this point my html is just a normal text area without those blocks or even the + symbol. If I refresh the page it works.

I hope I explained my issue clearly :)

**Comment by raffij** [comment]
Thanks for creating an issue for this.

The safest way you'll find to do this is use a textarea as a hidden storage for your data.

I guess you could do something similar to this?

```
function initSirTrevor(){
  editorSt = new SirTrevor.Editor(
    {
      el: $('.js-st-instance'),
      blockTypes: ['Text', 'Image', 'Heading'],
      required: ['Text']
    }
  );
}

scope.$watch('name', function(newValue) {
  $('.js-st-instance').val(newValue);
  if(SirTrevor.config.instances.length <= 0){
    initSirTrevor();
  }
  editorSt.reinitialize();
});

onButtonClick = function() {
  editorSt.onFormSubmit();
  var data = editorSt.store.toString();
  // Do something with your data.
}
```

**Comment by ilgianfra** [comment]
thanks,
right now still no success :) 
I am getting this javascript error:
Sorry there has been a problem with parsing the JSON
sir-trevor.js:3356 SyntaxError: Unexpected token o(…)

I keep trying!

**Comment by raffij** [comment]
Ok.

Can't help with that message.

if you inspect $('.js-st-instance') does it contain what you'd expect? as in the actual output of editorSt.store.retreive or .toString ?

**Comment by ilgianfra** [comment]
In your code you put a watch but what should i watch? one ng-model associated to my text-area in the html?
In  $('.js-st-instance') I have the html element.
I am thinking to create a plunker or similar to show you the issue.

Thanks for the support

**Comment by raffij** [comment]
My understanding of your issue is that you are binding a variable to the textarea and rendering the editor. The issue is the editor might be created before the data has been set. Then once the data is set you need to call reinitialize somewhere. As you've got ng-model="project._description" you'll want to watch the model and then when it changes call the instanance.reinitialize. You'll also want to make sure it's done after the textarea data has been updated. So the correct part of the digest.

If you are using angular < 2 then it's probably best creating a directive similar to the following:
http://stackoverflow.com/a/12021632

As your issue is now angularjs. Might be worth creating a stackoverflow for someone to respond to with specific angular knowledge. If you do that it would be good to update this issue with a link to that.

**Comment by ilgianfra** [comment]
I did that few days ago :)
http://stackoverflow.com/questions/33546629/edit-blocks-sir-trevor-with-angularjs

I will let you know if I get some news

**Comment by raffij** [comment]
Very sensible.

Should you not be calling the sir-trevor instance in the link phase, rather than controller?

**Comment by ilgianfra** [comment]
hmmm
I have tried that but it doesn't change the result.

calling it in the link phase should be different if you want to edit the element, I don't touch the element when I create the new blocks.
I am thinking that maybe I should compile the directive. I am gonna give a try

**Comment by raffij** [comment]
Proof of concept for you. https://github.com/raffij/sir-trevor-angular

**Comment by ilgianfra** [comment]
Thank you!!
I will try it out in these days!

**Comment by raffij** [comment]
I think the key for you is storing the instance somewhere that can be destroyed when the directive is destroyed.

I saw in one of your things that you are using `SirTrevor.getInstance()`. I'd replace this with storing the instance somewhere as a variable as that will be deprecated in the future.

So use something similar to `var editorSt = new SirTrevor.editor();` instead of `var editorSt = SirTrevor.getInstance();`

**Comment by ilgianfra** [comment]
Thanks! 
I have tried the repo and it looks very cool and working! 
I am gonna try to use the directive in my project, but if I need to get the new data from the editor I should use: ```SirTrevor.getInstance().store.retrieve()```? or is there another elegant way?
Because if I log the ngmodel i get undefined

thanks a lot

**Comment by raffij** [comment]
To get the new data you'll want:

editorSt.onFormSubmit();
var data = editorSt.store.retrieve();

Don't know what you mean by ngModel being undefined. Post your code once you've done that.

**Comment by ilgianfra** [comment]
hi! I am back! :)
You declare the var= editorSt globally and it is used inside the directive and the controller.
But if I want to use different instances of sirTrevor I can't access to the instance and send it to a server.
Btw I am gonna fork you repo for angular and use it with like firebase and like this you can see what I mean
