### ISSUE TITLE
Why do I get "Uncaught TypeError: Converting circular structure to JSON(…)"?

### ISSUE THREAD

**Issue by nilsi** [madebymany/sir-trevor-js#405]
Hi, 

Im trying to build a block for uploading multiple images. Uploading works and the block is updating but when I'm running ```instance.onFormSubmit();``` Im getting a circular structure problem. When I look at my generated data I find that the ```data``` entry indeed is circular:

![Image of problem](http://s4.postimg.org/zade5ci0d/Screen_Shot_2015_11_10_at_18_35_58.png)

But I can't figure out why. I based my block on cjbells multiple upload block:
https://gist.github.com/cjbell/7794216

Here is my block as it looks now:
http://pastebin.com/YDXvuBfX

I just started out building blocks and Im sure it's something simple but can't find it right now, any help would be appreciated.

**Comment by raffij** [comment]
@nilsi that gist looks quite old. I'd say it's incorrect and not the way to be dealing with data.

I think for consistency you want to call `getBlockData`. This will give you the data object, rather than the overall block object.

Then when saving if you want to load your loadData function again then use `setAndLoadData` otherwise `setData` will set your data, but not call that function.

The code can be found here:
https://github.com/madebymany/sir-trevor-js/blob/f0860db47f574c6ee2ded32353e5baa659f953e5/src/block-store.js#L36

Let me know how it goes.

**Comment by raffij** [comment]
Also are we linking to that block from somewhere?

**Comment by nilsi** [comment]
Thank you so much! Using those functions solved my problem. There are still some small stuff but think I can figure that out myself. 

Yes I thought that gist was outdated too. I found it here: https://github.com/madebymany/sir-trevor-js/issues/130

**Comment by raffij** [comment]
Ok. We'll leave that in place.
I'll get it edited at some point so it's better.

You'll want the multiple attribute:
http://www.w3schools.com/tags/att_input_multiple.asp

You might need to amend your onDrop function depending on how browsers send the data from the input field though.

When you are done close the issue.

**Comment by raffij** [comment]
Also if your block would be useful for others and is allowed to be shared then you could create a pr for this repo when done:
https://github.com/madebymany/sir-trevor-blocks

**Comment by nilsi** [comment]
Alright if I clean it up enough and put some ok representation of the block then I will do a PR for it. Thanks again for the help.
