### ISSUE TITLE
Image upload in 0.6

### ISSUE THREAD

**Issue by bigclumsyoaf** [madebymany/sir-trevor-js#453]
Hi, I'm looking to upgrade to 0.6, but I can't get the image uploader working with my application security. In 0.5, all cookies from the current page are sent with the upload. But it looks like switching to the new fetch api doesn't send these cookies.

Obviously for security we need the session cookie to upload a file. Is this a bug, or is there a way to attach all current page cookies to the image upload?

thanks

Daryl.

**Comment by SgtOddball** [comment]
You shouldn't need to reference the session cookie when uploading a file since the client-server connection should take care of that for you. 

Especially since polling anything sent to the server client side should never be trusted as far as you can throw it and thus sanitised with vengeance. Not to mention it would leave your users vulnerable to session hijacking (ie. you pass value 'x' as the clients user name, they reply with value 'y', a different account which is still valid but might have different authorisations thus allowing a 'naughty' process that shouldn't happen. All very easy with Dev tools and even big companies fall foul of this, just look at the recent issue with valves 'Steam' client). 

All you should be doing is checking the client has a valid session with the connection stream at the server side and taking only the barest minimum of inputs from the client side.

**Comment by raffij** [comment]
Great reasoning @SgtOddball 

I think what might be being requested is something like what is provided by various jquery helpers.

```javascript
SirTrevor.setDefaults({
  ajaxOptions: {
    headers: {
      "X-CSRF-Token": document.querySelector('meta[name=csrf-token]').getAttribute('content')
    },
    credentials: 'same-origin'
  },
});
```

**Comment by raffij** [comment]
That's a rails version

**Comment by bigclumsyoaf** [comment]
Hi, sorry I don't understand. That is my problem, with version 0.6 the session cookie is not being sent with the image upload request so it's being rejected by my server. I need the session to be sent with the file to authorise the upload.

**Comment by raffij** [comment]
https://github.com/github/fetch#sending-cookies

Decide on the option you need then add the following to your editor initialisation

```
SirTrevor.setDefaults({
  ajaxOptions: {
    credentials: 'same-origin'
  },
});

**Comment by bigclumsyoaf** [comment]
Great, that fixed it. Thanks a lot for your help!

**Comment by SgtOddball** [comment]
Ahh fair play, I've not used Rails before. Seems abit odd that you'd need to specify to transmit such details but I'll take it as a lesson learned.
