### ISSUE TITLE
Breaking content into A4-sized pages

### ISSUE THREAD

**Issue by zamakkat** [madebymany/sir-trevor-js#454]
I am currently working on integrating `sir-trevor` for our editor and was wondering if there was a way to achieve the stated functionality. Basically the UI should know when the content is longer than one page and break to next page (just like a native word editor). 

If anyone has any ideas or pointers on how to achieve this it would be great. I don't mind working on it and issuing a PR if it's not too complex.

**Comment by raffij** [comment]
Feels like this would be better as an output rather than a feature of the editor?

Something like print stylesheets, or calculate the height of blocks within your code and split as required.

In terms of code it's not something we'd accept as a PR, but is probably something you could patch on top of the current editor.

**Comment by zamakkat** [comment]
It needs to be both in the front-end (the editor) and in the back-end right? Because the user should be able to see when it breaks to the next page so they can edit accordingly?

Thanks anyway. Will have to figure out how to do this...
