### ISSUE TITLE
What's the latest stable release?

### ISSUE THREAD

**Issue by andrewsprinz** [madebymany/sir-trevor-js#456]
Oh hai. 

Which release are you guys using for production environments? 0.6 stable enough?

**Comment by raffij** [comment]
@andrewsprinz yeah we are using 0.6 latest beta from npm.

I've been meaning to do a final run through and then make it 0.6 final. Got a bit of time over the next couple of days. So i'll try to do that.

I've also been working on ie11+ polyfills and other changes which excluding paste are working as i'd expect.

You might find some block examples are out of date so ask if there's anything dodgy going on as the docs aren't for this version yet.

**Comment by andrewsprinz** [comment]
nice, thanks, will give 0.6 a whirl!

**Comment by raffij** [comment]
You'll also want:
https://github.com/madebymany/sir-trevor-js/blob/master/docs/migrations/0.5-0.6.md

**Comment by andrewsprinz** [comment]
thanks raffi +1 :thumbsup

**Comment by andrewsprinz** [comment]
0.6 is so so lovely guys 👏👌

**Comment by raffij** [comment]
Thanks @andrewsprinz. It's probably too opinionated at the moment as we reworked for our own use cases. Create issues for things you find weird, or pr them and i'll happily take a look.

**Comment by SgtOddball** [comment]
Which is why I'm holding off for the time being until I can sit down and go over the changes :confounded: :

**Comment by andrewsprinz** [comment]
I found 0.5 a bit of a pain to get going with, but 0.6.beta9 was so simple. Opinionated maybe, but so worth it.

I'm saying that having no custom blocks and not having to deal with IE though, privileged position :)

**Comment by SgtOddball** [comment]
Lucky you!

I've written/hacked/liberally borrowed a few different custom blocks as well as using @e1himself 's column block version (It would have gotten real messy trying to figure out how to add columns otherwise so it's been a real boon for offering different layout options). 

And yes I'll admit It's taken a while to understand half of whats going on with 0.5 but then it's pushed my knowledge of JS further so I can't really complain too much (though I'll admit I really could do with sitting down an ECMA 6 script manual for some light reading so I can follow whats going on more closely)
