### ISSUE TITLE
Polyfill for Object.assign

### ISSUE THREAD

**Issue by SgtOddball** [madebymany/sir-trevor-js#478]
I've had another user who wants to Safari to use Sir Trev, so again everything works nicely save for Scribe, which sort of works but then just stops when trying to apply styling. 

After having a further nosy around, the devs at Scribe pretty much state no safari, no IE but it to you want to support 'older' browsers then there's a list of polyfills of which currently only `Object.assign` is listed. 

So my thought was if Sir Trev is already using the file input API poly fill, could the Object.assign be added in as well and then harmony across browser could (possibly) be achieved? 

I would look further into it but time really isn't on my side at the moment and others might have  better/quicker thoughts on this?

**Comment by raffij** [comment]
Totally agree. I want IE support. unfortunately it looks like it has to be fixes to scribe rather than only shims.

I'm coming off a project very soon. So going to have some time to finally get 0.6 out and then look at the cross browser approach, as we've currently got a cross browser solution working, but want to improve it a little. I think it'll be some fixes to scribe in a fork, and then a shim js file in sir-trevor dist which is loaded prior to sir-trevor if cross browser is needed. The reasoning for this is 

There's a good fork at https://github.com/kencheeto/scribe

I made a fork of some of their changes too, which i'm using successfully in ie11 and other browsers. https://github.com/madebymany/scribe/kencheeto-ie-fixes

0.6 includes this shim. So i'd suggest adding it yourself in the wrapper app for now.

You'll also find scribe has been updated to v3. So it's feels like it's had a spur of interest from within guardian again. One of the changes has been to remove lodash, which will give us a smaller footprint in the future.

**Comment by SgtOddball** [comment]
Ahh, that'll help since I'm not a great fan of lodash. 

(Yes I know I use jQuery but thats about the only library I use, otherwise I'd go mad from trying to learn every single additional library and the mad quirks they have along with another level of abstraction before you give up and make a wonky bodge in javascript..</rant>). 

Now, if only we could ECMA6 on all browsers........ (though I need to learn more for that too *sigh*)

**Comment by bigclumsyoaf** [comment]
Awesome, thanks a lot!
