### ISSUE TITLE
How to add new icons?

### ISSUE THREAD

**Issue by morpheus-87** [madebymany/sir-trevor-js#480]
At the moment I'm working with version `0.5.0` and I want to add some custom blocks.
But I con't get a clue, how I can add new icons for these blocks.
Can somebody help me with that issue?

**Comment by raffij** [comment]
It's a bit of a challenge, but possible to add your own icons.

You'll want to download the svgs from https://github.com/madebymany/sir-trevor-js/tree/v0.5.0/public/images/icons/src

You can then use a service such as https://icomoon.io to import those svgs. Then produce the webfont required. You'll also need to modify the css to load the modified font you have created too.

**Comment by ninjabiscuit** [comment]
We really need to update the icon workflow. Been meaning to take a look at it for ages

-- 
Andrew Walker ["@ninjabiscuit", "07886655448"]
http://madebymany.com

On 1 July 2016 at 12:02:40, Raffi Jacobs (notifications@github.com) wrote:

It's a bit of a challenge, but possible to add your own icons.

You'll want to download the svgs from https://github.com/madebymany/sir-trevor-js/tree/v0.5.0/public/images/icons/src

You can then use a service such as https://icomoon.io to import those svgs. Then produce the webfont required. You'll also need to modify the css to load the modified font you have created too.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.


-- 
 

Made by Many Limited is registered in England and Wales (No.06346338). 
Registered office: Diespeker Wharf, 38 Graham Street, London, N1 8JX, UK

Made by Many Inc is registered in the State of New York (No.4427021). 65 
Greene Street, 4th Floor, New York, NY 10012, USA

**Comment by raffij** [comment]
@ninjabiscuit it's better now, but still not great.

This question is for 0.5 and therefore keeping it in as a reminder for me to document the latest process before the 0.6 release.

**Comment by ninjabiscuit** [comment]
:+1:

-- 
Andrew Walker ["@ninjabiscuit", "07886655448"]
http://madebymany.com

On 1 July 2016 at 12:23:39, Raffi Jacobs (notifications@github.com) wrote:

@ninjabiscuit it's better now, but still not great.

This question is for 0.5 and therefore keeping it in as a reminder for me to document the latest process before the 0.6 release.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


-- 
 

Made by Many Limited is registered in England and Wales (No.06346338). 
Registered office: Diespeker Wharf, 38 Graham Street, London, N1 8JX, UK

Made by Many Inc is registered in the State of New York (No.4427021). 65 
Greene Street, 4th Floor, New York, NY 10012, USA

**Comment by morpheus-87** [comment]
Thank you very much for this answer, that helped me quiet a lot!

But how do I get the generated woff file into the css?

**Comment by raffij** [comment]
You could redeclare the fontface with your woff or base64 font.

**Comment by morpheus-87** [comment]
Is it the right way to convert the woff into base64 with the bash tool **base64**?

Where do I have to add the result then? In the file `src/sass/_icons.scss`, right?

**Comment by raffij** [comment]
yes if you want to fork sir-trevor. Yeah that would work.
