### ISSUE TITLE
Missing delete button for blocks

### ISSUE THREAD

**Issue by morpheus-87** [madebymany/sir-trevor-js#486]
I've tested the current status of version 0.6.0-beta9 and noticed, that the delete button for blocks, which was available in 0.5.0, is missing.

**Comment by raffij** [comment]
0.6 has taken a slight change of direction for now. It's made to feel more like a structured document builder, rather than 0.5 which was more of an opinionated block manager.

Are you referring to the lack of delete blocks from text and list blocks? Or maybe there is a bug you are observing.

**Comment by raffij** [comment]
Also will the functionality / styling of 0.6 work with your current thinking, or should we create a 0.5.1 for you with the pull request you submitted? #409

**Comment by morpheus-87** [comment]
Thank you very much for your answer!

![sir-trevor-0 5 0](https://cloud.githubusercontent.com/assets/19190936/16646573/0d169108-442b-11e6-9031-9be6501389d8.png)

![sir-trevor-0 6 0-beta10](https://cloud.githubusercontent.com/assets/19190936/16646574/11539662-442b-11e6-86d3-b2953d39d0a6.png)

I was talking about the button marked in the first screenshot with the red arrow - with that button, that was available, it was possible to delete a block again. The button marked in the screenshots with the green arrow - used to position a block - is available in either 0.5.0 and 0.6.0-beta10.

Is it planned to include the button for deleting blocks in release 0.6.0?

**Comment by raffij** [comment]
The reasoning behind that not being available is text blocks are now a
paragraph of text rather than a large body of text. As a result it feels
more likely that users will edit multiple blocks as a complete body of text
using my the keyboard.

There are ways that this could be enabled using css, or if we see enough
demand adding in a config option to show this, but at the moment the
default is to not have these present on text or listing blocks.

**Comment by morpheus-87** [comment]
Thank you for the explanation. I think, now I got the trick. So you can delete a text or a list block by removing all of the content, right?

**Comment by raffij** [comment]
Yes. Think of it more like an editor like medium. I'll be available next
week to provide support on changes to css and others that will help you get
the delete icons back if you like.

**Comment by raffij** [comment]
If you want to reintroduce the delete button on text / list blocks you can do so as follows:

```
.st-block .st-block-ui-btn__delete {
  display: block !important;
}
```

**Comment by morpheus-87** [comment]
Thank you very much for that advise, @raffij!

But when I start typing some text, I run into problems, see this screenshot:

![block](https://cloud.githubusercontent.com/assets/19190936/16731426/4e6c9e72-4778-11e6-95c6-2feab8fee9f7.png)

As you can see, the `x` gets cut off. I had to add

```css
.st-block {
  min-height: 55px;
}
```

to get it working.

**Comment by raffij** [comment]
Yeah with 0.6 we've made some decisions which mean putting things back might not work great for now.

Either do this if it still makes the paragraph spacing feel ok, or how about absolute position that to the left of the drag area?

I've put a milestone of 0.6.2 in to make this work along with drag / drop improvements. That'll be completed by the end of the month. We'll also bee looking at design of it at the same time which will help.

Feel free to add other issues and i'll add them to a relevant milestone.

For the moment keep it in your code and we'll make some changes in a couple of week.

**Comment by raffij** [comment]
Also for your info https://github.com/madebymany/sir-trevor-js/milestones

**Comment by morpheus-87** [comment]
What is the current status of this issue, @raffij?

**Comment by raffij** [comment]
@morpheus-87 we haven't had time to look at the design and implementation yet. Should I give some assistance to override for now?

**Comment by ToBe998** [comment]
I can understand the reasoning about removing the "delete" button from text blocks, but apart from my opinion on that, it seems impossible to remove a text block now. Even removing all content does not delete it. Removing all content just re-displays the green type-selector icon on the left.
So in short, removing is not possible atm.

So in short, this does not seem to be a design issue at this time but a missing functionality that is actually very important. Can we put a bit more priority on that?

**Comment by raffij** [comment]
@ToBe998 Thanks for the feedback. Sounds like your feedback is in relation to the default behaviour in the latest version.

Are you using sir-trevor as a block editor? if so that's definately something we'll be addressing in the future.

We need to look at how we can support that whilst continuing in a direction that better fits our existing and future clients. Which as you'll see is more inline with medium or dropbox paper.

**Comment by ToBe998** [comment]
Yes, we want to use sir-trevor as block editor. So basically as a editor that allows users to edit their content in a freeform way and still only have clearly structured json in the database.

It's a replacement for the typical HTML based WYSIWYG editors like CKEdit and similar, which only create unstructered html that can not be propery parsed in cms systems.

**Comment by raffij** [comment]
Ok that makes sense and the reasoning behind why the existence of a text block at all times might cause you issues.

Are you aware a text block is sort of a starter block at present? empty text blocks are filtered from the json and can be replaced with any other block from the block selector.

Let me have a look if there's anything you might be able to do for now.

**Comment by ToBe998** [comment]
Yes, i noticed the change in your UX concept. ;)
problem is, since the empty block will stay in place visually, it will confuse the users.

**Comment by raffij** [comment]
Ok. I'll have a think.

**Comment by ToBe998** [comment]
Just noticed that you can in fact press backspace one more time on text blocks and they vanish. In addition to that, i followed above advice on making the delete button visible (and tweaking it's position) and that also worked. So, my problem is fixed, tnx there! 
Still looking forward to see were the final UX concept will be heading if it's still in flux. ;)

**Comment by SgtOddball** [comment]
Regarding this issue I've started to create a few sites with the new UX and yeah, I agree it's confusing for users for a few reasons (I'm not trying to rant, just attempting to give reasonable pointers). 

1. No indication of 'blocks' any more (no borders or some such) other than the dots in the top right hand corner. Doesn't indicate very well that each block is a separate entity and should be treated as such.
2. Adding further blocks not obvious. Without moving the mouse over to an area where a line appears (which isn't very tall so easily missed/difficult to click on for the less nimble mouse manipulators) there's nothing to indicate that further blocks can be added/inserted - Scratch that... just found the add button at the bottom when testing on my phone, in which case it's not the greatest contrast in the world so could do with a colour change (See, sometimes it's simple).  
3. As mentioned deleting blocks. Sometimes you just want the block to disappear and it's not obvious how to achieve this in a single motion - Only the video blocks seem to have a delete button available. 
4. Mobile devices require a double tap before the toolbar shows up and when it does it doesn't wrap. Admittedly I know that mobile devices aren't the focus point of the project so it's not such a great concern - I might look further into this now I've got some free time to brush up on browser skills. 
5. Possibly more a scribe issue - android/iOS inconsistencies with the tool bar. Android gets the one that looks like you would on a desktop machine whilst iOS gets a toolbar that looks like the default iOS one (so no insert link button or quote button).

 
Now on the plus side (see I'm not so negative);
1. Interface does feel cleaner, so that Sir trev is much more part of the background like the browsers are supposed to do that rather than it be a plugin. 
2. Looks good on mobiles. 
3. Doesn't seem to have any issues with large amounts of content (v.0.5 sometimes judders abit if you're throwing a lot of content at it).
