### ISSUE TITLE
Link targets/opening in _blank

### ISSUE THREAD

**Issue by bigclumsyoaf** [madebymany/sir-trevor-js#527]
Hi, a client is wanting us to change the link functionality to be able to select the link target. 

I found this old issue which shows examples of extending links:
https://github.com/madebymany/sir-trevor-js/issues/203

But the latest version just uses a default javascript prompt for the URL input. Do you have any examples of extending this into a modal to give extra options? Or any pointers where to start?

thanks

Daryl.

**Comment by raffij** [comment]
@bigclumsyoaf late reply, but wanted to close this up with an answer.

We use scribe as an text editing interface, which uses the `scribe-plugin-link-prompt-command` to provide the interface to enter the link text that you are wanting to extend.

In order to do this you'll want to modify the functionality of the following module to allow entry of a target as well as a link.

https://github.com/guardian/scribe-plugin-link-prompt-command/blob/master/src/scribe-plugin-link-prompt-command.js

At the moment this module is included here:
https://github.com/madebymany/sir-trevor-js/blob/b28af9e608b736ed495944df94ad54eec55c9d06/src/scribe-interface.js#L44

However this could be moved to be configurable in your own fork of sir-trevor or possibly contributed back to sir-trevor-js if you wanted.
