### ISSUE TITLE
Paste over selected text splits into new block

### ISSUE THREAD

**Issue by ToBe998** [madebymany/sir-trevor-js#543]
If you paste a snippet of text (even only a single word without any formatting) over a selected word within a text block, it will split the text block in three blocks. The one before selection, the pasted text, the part after the selection.

What it should do is just replacing the selected text without changing blocks in any way.

- Chrome
- Mac OS
- Sir-Trevor v0.6.6

**Comment by pfinkbeiner** [comment]
Hm, I would love to help out but I cant confirm it as a bug. Have you tried to clone the repo and navigate to `http://127.0.0.1:8080/examples/` after run `npm run dev` to ensure its a bug and not some side effects?

**Comment by ilyaporopudas** [comment]
Can't reproduce, might've been fixed since?

**Comment by raffij** [comment]
Pretty sure it’s valid when you paste in a certain scenario

**Comment by raffij** [comment]
This was most obvious in firefox.

The issue was when you paste a piece of text it's wrapped in a p tag. Then when scribe inserts that p tag into the block it forces the outer p tag into 3 sequential p tags making 3 blocks.

There's a fix coming in a future release that deals with pasting of sir-trevor block content.

**Comment by ToBe998** [comment]
Was also just recently able to reproduce this. Only on Mac/Chrome and Mac/Safari did the <p> thing. Windows/Chrome was working fine.
