### ISSUE TITLE
Project still alive / maintained?

### ISSUE THREAD

**Issue by JanLoebel** [madebymany/sir-trevor-js#547]
Hi everyone,

it looks like the project is kind of dead? Is there still somebody maintaining it? Just wanted to know before I start using it :) It was exactly what I was looking for ;)

Best regards,
Jan

**Comment by marioschubert** [comment]
Hi,

I am using it and currently working heavily on it. Perparing full block mode. A material look. Some nice blocks. Responsive. And more. If there is interest,  to work together on it,  I would be very happy. 

Best regards 
Mario

**Comment by JanLoebel** [comment]
Hi @marioschubert ,

currently, I'm new to the rich text editor stuff and was looking around for alternatives like Draft.Js and Slate. I really liked the demo of what can be done by "Sir Travor JS".

Can you explain me quickly what "full block mode" means? :)

**Comment by marioschubert** [comment]
Hi @janloebel,

the current release of Sir Trevor focuses on document mode. You type text more like a normal rich text editor. If you  need a list or an image, you have to replace the text block. 
In block mode you first select the type of block you want and type in this block. I personally like this approach to augment structured thinking before you type. I will post an example video soon.

Best regards 
Mario

**Comment by zyuhel** [comment]
Hi @marioschubert will your commits be added to current repo? or they will be in your fork only?

**Comment by ToBe998** [comment]
We are currently using this very heavily in our cms. Also with many custom blocks for various things like oembeds and imagelists. So, highly interest into continuation of this project or a hopefully mostly compatible successor :)

**Comment by prwhitehead** [comment]
@ToBe998 are any of those Blocks available open source?

**Comment by ToBe998** [comment]
One or two are, but all of them are only usable within the Bolt cms. We use Sir-Trevor as a custom field type there.

**Comment by prwhitehead** [comment]
Thanks for replying. 

If I search within Bolts code will I find them there? I'm trying to make some customer Blocks for a client and Sir Trevor is a mess of outdated examples.

**Comment by prwhitehead** [comment]
@rossralev would you be keen on open sourcing some of your blocks so that there are some more up to date example Blocks available for people just now finding the project?

**Comment by raffij** [comment]
SirTrevor is still alive and maintained as needed.

The principles still hold true and exist in lots of different places these days. Even Wordpress has adopted a similar approach https://wordpress.org/gutenberg/

As you've seen it's not in active development at present, but that's because it does what we need. When we find issues we prioritise and submit pr's when appropriate.

If you'd like to contribute to changes then i'd suggest creating an issue for discussion as SirTrevor has always been opinionated and will continue to be.

@prwhitehead what sort of sample blocks are you looking for?, and if you find any then you are more than welcome to add them to https://github.com/madebymany/sir-trevor-blocks
